name: 'pureflow_dbt'
version: '1.0.0'
config-version: 2

profile: 'pureflow'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  pureflow_dbt:
    sales:
      +materialized: table
      +schema: gold
      gold:
        +materialized: external
        +format: parquet
        +location: "s3://gold/{{ model.name }}/dt={{ var('execution_date', '2026-04-15') }}/{{ model.name }}.parquet"
