services:
  # --- MINIO: Our "External" S3 Storage ---
  minio:
    image: quay.io/minio/minio:latest
    container_name: pureflow_storage
    ports:
      - "9000:9000" # API
      - "9001:9001" # Web Console
    environment:
      MINIO_ROOT_USER: ${STORAGE_USER}
      MINIO_ROOT_PASSWORD: ${STORAGE_PASSWORD}
    volumes:
      - ./data/minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pureflow_net

  # --- CREATE AIRFLOW instance ---
  airflow:
    image: apache/airflow:2.7.1-python3.11
    container_name: pureflow_airflow
    # Run as host user UID 1000 to avoid permission issues with mounted volumes
    user: "1000:0"
    environment:
      - AIRFLOW_HOME=/opt/airflow/.airflow
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER:-airflow}:${POSTGRES_PASSWORD:-airflow}@postgres:5432/${POSTGRES_DB:-airflow}
      - AIRFLOW_UID=1000
      - PYTHONPATH=/opt/airflow/src
      - _PIP_ADDITIONAL_REQUIREMENTS=duckdb dbt-duckdb duckdb-engine great-expectations pandas>=2.2.2 numpy<2.0.0 deltalake python-dotenv
      - STORAGE_USER=${STORAGE_USER}
      - STORAGE_PASSWORD=${STORAGE_PASSWORD}
      - S3_ENDPOINT=http://minio:9000
    volumes:
      - .:/opt/airflow
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    command: standalone
    networks:
      - pureflow_net

  postgres: # Necessary for Airflow metadata
    image: postgres:13
    container_name: pureflow_metadata
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-airflow}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-airflow}
      - POSTGRES_DB=${POSTGRES_DB:-airflow}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-airflow}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pureflow_net

  # --- APP: The Dev Environment (Python, dbt, GX) ---
  app:
    build: .
    container_name: pureflow_app
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - pureflow_net
    stdin_open: true
    tty: true

networks:
  pureflow_net:
    driver: bridge
