version: 2

sources:
  - name: silver
    schema: main
    tables:
      - name: vendas
        external_location: "s3://silver/erp_vendas/dt=2024-03-29/"
        # We use delta_scan in DuckDB, dbt-duckdb handles this via 'external_location'
        # Or we can use direct SQL in models.
      - name: clientes
        external_location: "s3://silver/crm_clientes/dt=2024-03-29/"
