services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: data_lake_storage
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console UI
    environment:
      MINIO_ROOT_USER: ${STORAGE_USER}
      MINIO_ROOT_PASSWORD: ${STORAGE_PASSWORD}
    volumes:
      - ./data/minio_data:/data
    command: server /data --console-address ":9001"

  app:
    build: .
    container_name: gatekeeper_app
    volumes:
      - .:/app
    environment:
      - ENV_FOR_DYNACONF=development
    depends_on:
      - minio
    stdin_open: true
    tty: true