version: 2

models:
  - name: vendas_silver
    description: |
      ### Camada Silver (Standardization & Cleaning)
      **Propósito:** Limpeza de dados e aplicação de tipos corretos.
      **Validação de Qualidade (GX):** Garante que não há valores negativos e que as datas estão no formato correto após o casting.
    columns:
      - name: sale_value
        description: "Valor da venda convertido para DECIMAL(18,2)."
      - name: sale_date
        description: "Data da venda convertida para DATE."

  - name: clientes_silver
    description: "Dados de clientes limpos e com e-mail validado."
    columns:
      - name: email
        description: "E-mail do cliente (deve seguir padrão regex)."
